--Games--
INSERT INTO game (title, description, image, link)
VALUES ('Honkai Impact 3rd', 'You are playing as the valkyries', '/images/hi3rd/Honkai Impact 3rd Cover.webp', '/hi3rd'),
       ('Genshin Impact', 'Playing as the traveller', '/images/gi/Genshin Impact Cover.webp', '/gi'),
       ('Honkai Star Rail', 'You are a stellaron and joined the Express', '/images/hsr/Honkai Star Rail Cover.jpg', '/hsr'),
       ('Zenless Zone Zero', 'You are a wanted criminal', '/images/zzz/Zenless Zone Zero Cover.webp', '/zzz');

--Categories--
INSERT INTO category (type, description)
VALUES ('Plushies', 'A doll made out of cotton'),
       ('Figurines', 'Mainly made with pvc'),
       ('Key-Chains', 'Mainly made of arcylic plastic'),
       ('Posters', 'A drawing of someone or a landscape');

--Characters--
INSERT INTO game_character (name, description)
VALUES
    --HI3rd--
/*1*/  ('Kiana Kaslana', ''),
/*2*/  ('Bronya Zaychik', ''),
/*3*/  ('Raiden Mei', ''),
/*4*/  ('Elysia', ''),
/*5*/  ('Senti', ''),
/*6*/  ('Griseo', ''),
/*7*/  ('Vii', ''),
/*8*/  ('Mobius', ''),
/*9*/  ('Fu Hua', ''),
/*10*/ ('Aponia', ''),
/*11*/ ('Yae Sakura', ''),
/*12*/ ('Eden', ''),
/*13*/ ('Kosma', ''),
    --GI--
/*14*/ ('Arlecchino', ''),
/*15*/ ('Hu Tao', ''),
/*16*/ ('Diluc', ''),
/*17*/ ('Furina', ''),
/*18*/ ('Raiden Ei', ''),
/*19*/ ('Zhongli', ''),
/*20*/ ('Venti', ''),
/*21*/ ('Fischl', ''),
/*22*/ ('Kazuha', ''),
    --HSR--
/*23*/ ('Kafka', ''),
/*24*/ ('Blade', ''),
/*25*/ ('Jingliu', ''),
/*26*/ ('Jing Yuan', ''),
/*27*/ ('Feixiao', ''),
/*28*/ ('Firefly', ''),
/*29*/ ('Herta', ''),
/*30*/ ('HuoHuo', ''),
/*31*/ ('Dan Heng', ''),
/*32*/ ('Bailu', ''),
/*33*/ ('Luocha', ''),
/*34*/ ('Yun Li', ''),
    --ZZZ--
/*35*/ ('Koleda Belabog', ''),
/*36*/ ('Grace Howard', ''),
/*37*/ ('Anton Ivanov', ''),
/*38*/ ('Ben Biggers', ''),
/*39*/ ('Nicole Demara', ''),
/*40*/ ('Anby Demara', ''),
/*41*/ ('Ellen Joe', ''),
/*42*/ ('Rina', ''),
/*43*/ ('Corin Wickes', ''),
/*44*/ ('Zhu Yuan', ''),
/*45*/ ('Belle', ''),
/*46*/ ('Wise', '');

--Outfits--
INSERT INTO outfit (name, description)
VALUES
    --HI3rd--
        ('White Comet', ''),
        ('Void Drifter', '');
    --GI--

--Product--
INSERT INTO product (name, price, description, image, GAME_ID, CATEGORY_ID)
VALUES
    --Honkai Impact 3rd--
        ('Trio Poster', 17.5, 'Made with cotton', '/images/hi3rd/Friend group poster.jpg',1, 4),
        ('Griseo Key-Chain', 15, 'It is arcylic plastic and contains 2 key-chains', '/images/hi3rd/Griseo key chain set.jpg', 1, 3),
        ('Herrscher of Finality figurine', 18, 'Made out of pvc', '/images/hi3rd/Herrscher of Finality figurine.jpg', 1, 2),
        ('Herrscher of the Void figurine', 17, 'Made out of pvc', '/images/hi3rd/Herrscher of the Void figurine.webp', 1, 2),
        ('Honkai Impact Key-Chain set', 20, 'Arcylic plastic key-chains', '/images/hi3rd/keychain set.jpg', 1, 3),
        ('Kiana Kaslana Poster', 15.5, 'Paper poster', 'images/hi3rd/Kiana Kaslana Poster.jpg', 1, 4),
        ('Mobius poster set', 60, 'Contains 6 posters!', 'images/hi3rd/Mobius Poster set.jpg', 1, 4),
        ('Plush set', 30, 'Made with cotton', '/images/hi3rd/Plush set.jpg', 1, 1),
        ('Raiden Mei Figurine', 16, 'Made with pvc', '/images/hi3rd/Raiden Mei Figurine.jpg', 1, 2),
        ('Raiden Mei Poster', 14, 'Poster made out of paper', '/images/hi3rd/Raiden Mei Poster.jpg', 1, 4),
    --Genshin Impact--
        ('Archons Poster', 20, '1 poster of 3 archons together', '/images/gi/Archons Poster.webp', 2, 4),
        ('Arlecchino Figurine.webp', 25, 'made with pvc', '/images/gi/Arlecchino Figurine.webp', 2, 2),
        ('Arlecchino key-chain', 12, 'Arcylic plastic', '/images/gi/Arlecchino key chain.jpg', 2, 3),
        ('Diluc Plush', 13.5, 'Cotton doll', '/images/gi/Diluc Plush.jpg', 2, 1),
        ('Fischl Figurine', 24.5, 'made with pvc', '/images/gi/Fischl Figurine.jpg', 2, 2),
        ('Fischl Poster', 11.5, 'paper poster', '/images/gi/Fischl Poster.jpg', 2, 4),
        ('Furina key-chain set', 20, 'contains 8 key-chains of Furina', '/images/gi/Furina Key chain Set.jpg', 2, 3),
        ('Furina Plush', 13, 'cotton doll', '/images/gi/Furina Plush.jpg', 2, 1),
        ('Hu Tao Figurine', 22, 'pvc figurine', '/images/gi/Hu Tao Figurine.webp', 2, 2),
        ('Kazuha Poster', 14.5, 'paper poster', '/images/gi/Kazuha Poster.jpg', 2, 4),
    --Honkai Star Rail--
        ('Honkai Star Rail plush set', 20, 'Cotton Plush set', '/images/hsr/4 plush set.webp', 3, 1),
        ('Feixiao Figurine', 27, 'pvc figurine', '/images/hsr/Feixiao Figurine.webp', 3, 2),
        ('Firefly Poster', 16.5, 'paper poster', '/images/hsr/Firefly Poster.jpg', 3, 4),
        ('Herta Figurine', 23, 'made out of pvc', '/images/hsr/Herta Figurine.webp', 3, 2),
        ('Herta Poster', 14, 'paper poster', '/images/hsr/Herta Poster 2.jpg', 3, 4),
        ('HuoHuo Figurine', 40, 'Made with pvc', '/images/hsr/HuoHUo figurine.jpg', 3, 2),
        ('HuoHuo key-chains set', 20, 'Arcylic key-chains', '/images/hsr/HuoHuo keychain set.jpg', 3, 3),
        ('HuoHuo plush', 12, 'made with cotton', '/images/hsr/HuoHuo plush.jpg', 3, 1),
        ('Honkai Star Rail plush set', 24, 'cotton plushies', '/images/hsr/Star Rail plush set.jpg', 3, 1),
        ('Yunli Poster', 14.5, 'paper poster', '/images/hsr/Yunli Poster.jpg', 3, 4),
    --Zenless Zone Zero--
        ('Sibling Poster' , 10, 'paper poster', '/images/zzz/Wise Belle.webp', 4, 4),
        ('Anby Figurine', 21, 'pvc doll', '/images/zzz/Anby Figurine.webp', 4, 2),
        ('Belabog Industries Poster', 12.5, 'paper poster', '/images/zzz/Belabog poster.jpg', 4, 4),
        ('Corin key-chains set', 18, 'key-chains set', '/images/zzz/Corin Key Chain set.jpg', 4, 3),
        ('Ellen Joe Figurine', 27.5, 'pvc doll', '/images/zzz/Ellen Joe Figurine.jpg', 4, 2),
        ('Rina Figurine', 26, 'pvc doll', '/images/zzz/Rina Figurine.webp', 4, 2),
        ('Sibling Poster 2', 11, 'paper poster', '/images/zzz/Belle and Wise poster.jpeg', 4, 4),
        ('Zenless Zone Zero key-chains set', 13, 'key-chains set', '/images/zzz/zzz keychains set.webp', 4, 3),
        ('Zenless Zone Zero plushies', 18, 'plushie set', '/images/zzz/zzz plush.jpeg', 4, 1),
        ('Ellen Plush', 16, 'plushie of cotton, attachable tail', '/images/zzz/Ellen Plush.webp', 4, 1);

INSERT INTO PRODUCT_GAME_CHARACTERS (PRODUCTS_ID, GAME_CHARACTERS_ID)
VALUES
    --Honkai Impact 3rd--
        (1, 1),
        (1, 2),
        (1, 3),
        (2, 6),
        (3, 1),
        (4, 1),
        (5, 2),
        (5, 3),
        (5, 4),
        (5, 5),
        (5, 9),
        (5, 7),
        (6, 1),
        (7, 8),
        (8, 6),
        (8, 7),
        (8, 9),
        (8, 10),
        (8, 11),
        (8, 12),
        (8, 13),
        (9, 3),
        (10, 3),
    --Genshin Impact--
        (11, 18),
        (11, 19),
        (11, 20),
        (12, 14),
        (13, 14),
        (14, 16),
        (15, 21),
        (16, 21),
        (17, 17),
        (18, 17),
        (19, 15),
        (20, 22),
    --Honkai Star Rail--
        (21, 23),
        (21, 24),
        (21, 25),
        (21, 26),
        (22, 27),
        (23, 28),
        (24, 29),
        (25, 29),
        (26, 30),
        (27, 30),
        (28, 30),
        (29, 24),
        (29, 25),
        (29, 33),
        (29, 31),
        (29, 32),
        (29, 29),
        (29, 23),
        (30, 34),
    --Zenless Zone Zero--
        (31, 45),
        (31, 46),
        (32, 40),
        (33, 35),
        (33, 36),
        (33, 37),
        (33, 38),
        (34, 43),
        (35, 41),
        (36, 42),
        (37, 45),
        (37, 46),
        (38, 36),
        (38, 39),
        (38, 41),
        (38, 42),
        (38, 44),
        (38, 45),
        (38, 46),
        (39, 39),
        (39, 40),
        (39, 41),
        (39, 43),
        (39, 44),
        (40, 41);